In [1]:
# Exp 5

In [2]:
#Aim : Creation of array using numpy

In [3]:
#Name:Punam Khotele
#Year:3^rd
#Sec:C
#Roll No.:30
#sub:ET-I

In [4]:
import numpy as np

# Creation of ID array

In [5]:
arr1 = np.array([1,2,3,4,5])

In [6]:
print(arr1)

[1 2 3 4 5]


# Creating a 2D array

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [8]:
print(arr2)

[[1 2 3]
 [4 5 6]]
